if not SERVER then return end

-- Do not edit this file if you dont know what you are doing

-- Get all stats

function PSTATS_DATA:GetKills(id64)
  return PSTATS_DATA.cache_table[tostring(id64)].kills
end

function PSTATS_DATA:GetHeadshots(id64)
  return PSTATS_DATA.cache_table[tostring(id64)].headshots
end

function PSTATS_DATA:GetDeaths(id64)
  return PSTATS_DATA.cache_table[tostring(id64)].deaths
end

function PSTATS_DATA:GetWins(id64)
  return PSTATS_DATA.cache_table[tostring(id64)].wins
end


-- Add to stats

function PSTATS_DATA:AddKills(id64, value)
  if not PSTATS_DATA:IsCached(id64) then return end
  PSTATS_DATA.cache_table[tostring(id64)].kills = PSTATS_DATA.cache_table[tostring(id64)].kills+value
end

function PSTATS_DATA:AddHeadshots(id64, value)
  if not PSTATS_DATA:IsCached(id64) then return end
  PSTATS_DATA.cache_table[tostring(id64)].headshots = PSTATS_DATA.cache_table[tostring(id64)].headshots+value
end

function PSTATS_DATA:AddDeaths(id64, value)
  if not PSTATS_DATA:IsCached(id64) then return end
  PSTATS_DATA.cache_table[tostring(id64)].deaths = PSTATS_DATA.cache_table[tostring(id64)].deaths+value
end

function PSTATS_DATA:AddWins(id64, value)
  if not PSTATS_DATA:IsCached(id64) then return end
  PSTATS_DATA.cache_table[tostring(id64)].wins = PSTATS_DATA.cache_table[tostring(id64)].wins+value
end
